// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api/authentication.mdx": () => import("../content/docs/api/authentication.mdx?collection=docs"), "api/collect.mdx": () => import("../content/docs/api/collect.mdx?collection=docs"), "api/dashboard-api.mdx": () => import("../content/docs/api/dashboard-api.mdx?collection=docs"), "api/errors.mdx": () => import("../content/docs/api/errors.mdx?collection=docs"), "api/index.mdx": () => import("../content/docs/api/index.mdx?collection=docs"), "api/projects.mdx": () => import("../content/docs/api/projects.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/your-first-project.mdx": () => import("../content/docs/getting-started/your-first-project.mdx?collection=docs"), "guides/nextjs.mdx": () => import("../content/docs/guides/nextjs.mdx?collection=docs"), "guides/react.mdx": () => import("../content/docs/guides/react.mdx?collection=docs"), "guides/self-hosting.mdx": () => import("../content/docs/guides/self-hosting.mdx?collection=docs"), "guides/vue.mdx": () => import("../content/docs/guides/vue.mdx?collection=docs"), "concepts/data-model.mdx": () => import("../content/docs/concepts/data-model.mdx?collection=docs"), "concepts/events.mdx": () => import("../content/docs/concepts/events.mdx?collection=docs"), "concepts/security.mdx": () => import("../content/docs/concepts/security.mdx?collection=docs"), "concepts/sessions.mdx": () => import("../content/docs/concepts/sessions.mdx?collection=docs"), "sdk/api-reference.mdx": () => import("../content/docs/sdk/api-reference.mdx?collection=docs"), "sdk/auto-tracking.mdx": () => import("../content/docs/sdk/auto-tracking.mdx?collection=docs"), "sdk/configuration.mdx": () => import("../content/docs/sdk/configuration.mdx?collection=docs"), "sdk/index.mdx": () => import("../content/docs/sdk/index.mdx?collection=docs"), "sdk/performance.mdx": () => import("../content/docs/sdk/performance.mdx?collection=docs"), "sdk/revenue-tracking.mdx": () => import("../content/docs/sdk/revenue-tracking.mdx?collection=docs"), "sdk/spa-support.mdx": () => import("../content/docs/sdk/spa-support.mdx?collection=docs"), "sdk/tracking-events.mdx": () => import("../content/docs/sdk/tracking-events.mdx?collection=docs"), "sdk/user-identification.mdx": () => import("../content/docs/sdk/user-identification.mdx?collection=docs"), }),
};
export default browserCollections;